# Point the "latest release" readme link at the new tag
pre_commit = sed -i "" "s|netbsd-builder/blob/v$RELEASE_PREV_VERSION/readme.md|netbsd-builder/blob/v$RELEASE_VERSION/readme.md|g" readme.md
pre_commit = git add readme.md
